#!/usr/bin/bash

if [ "$#" -ne 1 ]; 
then
    echo "Usage: $0 <file>"
exit 1

FILE="$1"

while read -r NUMBER; do

    FACTORS=($(factor "$NUMBER"))

    FACTOR1=${FACTORS[1]}
    FACTOR2=${FACTORS[2]}

    echo "$NUMBER=$FACTOR1*$FACTOR2"
done < "$FILE"
